#!/usr/bin/env bash

script_name="$0"
script_basedir=$(dirname `which $0`)
indexes_file="${HOME}/.investing_com.indexes"
scrapy_folder="${HOME}/self/investing.com/spiders/"

#
# Needs from apt:
#   + gridsite-clients
#
#

function usage
{
    echo -e "[Usage]:\n\t${script_name} pair (over/under) price [message]\n"
    echo -e "\t${script_name} pair around price step N_steps\n"
    echo -e "\t${script_name} pair around price step N_steps-UP N_steps-DOWN\n"
    echo -e "\t${script_name} view pair1,pair2,pair3 (default to all)\n"
}

function match_pair
{
    if [ ! -e "${indexes_file}" ]; then
	echo "[error] Hmm, could not find pairs indexes file: ${indexes_file}"
	exit 1
    fi
    
    pair=$(grep "${1}=" "${indexes_file}" | sed -e 's/'${1}'=\(.*\)/\1/')
    if [ -z "$pair" ]; then
	echo "[error] Oops, pair not found: '${1}'"
	usage
	exit 1
    fi
}

function match_pairs
{
    if [ ! -e "${indexes_file}" ]; then
	echo "[error] Hmm, could not find pairs indexes file: ${indexes_file}"
	exit 1
    fi

    pairs=""
    for i in $(echo "$1" | sed "s/,/ /g"); do
	pair=$(grep "${i}=" "${indexes_file}" | sed -e 's/'${i}'=\(.*\)/\1/')
	if [ -n "$pair" ]; then
	    if [ -z "$pairs" ]; then
		pairs="$pair"
	    else
		pairs="$pairs,$pair"
	    fi
	fi
    done
}

function match_action
{
    action="$1"
    if [ "$action" == "over" ] || [ "$action" == "under" ]; then
	true;
    else
	echo "[error] Unknown action: '${action}'"
	usage
	exit 1
    fi
}

function send_alert
{
    # $pair must be set
    # over/under price msg
    
    curl 'https://www.investing.com/useralerts/service/create' \
	 -H 'Connection: keep-alive' \
	 -H 'Accept: */*' \
	 -H 'X-Requested-With: XMLHttpRequest' \
	 -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36' \
	 -H 'Content-Type: application/x-www-form-urlencoded' \
	 -H 'Origin: https://www.investing.com' \
	 -H 'Sec-Fetch-Site: same-origin' \
	 -H 'Sec-Fetch-Mode: cors' \
	 -H 'Sec-Fetch-Dest: empty' \
	 -H 'Referer: https://www.investing.com/members-admin/alert-center' \
	 -H 'Accept-Language: en-US,en;q=0.9,pt;q=0.8' \
	 -H "Cookie: ses_id=${INVESTING_COM_SID}" \
	 --data-raw "alertType=instrument&alertParams%5Bpair_ID%5D=${pair}&alertParams%5Bvalue%5D=${2}&alertParams%5Balert_trigger%5D=price&alertParams%5Bfrequency%5D=Once&alertParams%5Bthreshold%5D=${1}&alertParams%5Bplatform%5D=desktop&alertParams%5Bemail_alert%5D=No&alertParams%5BpreReminderText%5D=${3}" \
	 --compressed

    echo ""
}

function generate_alert_around
{
    a_price="$1"
    a_step="$2"

    n_steps_up="$3"
    n_steps_down="$4"

    if [ -z "$n_steps_down" ]; then
	n_steps_down="$3"
    fi

    echo -e "[debug] Generating alert with base price as ${a_price} with ${a_step}:\n\tUP <- ${n_steps_up}\n\tDOWN <- ${n_steps_down}\n"

    for i in $(seq 1 "$n_steps_up"); do
	c_price=$(echo "${a_price} + (${a_step} * ${i})" | bc)
	echo "[debug] Sending alert for price over ${c_price}"
	send_alert "over" "$c_price"
    done

    for i in $(seq 1 "$n_steps_down"); do
	c_price=$(echo "${a_price} - (${a_step} * ${i})" | bc)
	echo "[debug] Sending alert for price under ${c_price}"
	send_alert "under" "$c_price"
    done

}

function view_alerts
{
    tmp_output_dir="${HOME}/tmp/scrapy/"
    tmp_output_jsonfile="${tmp_output_dir}/investing.com_alerts_`date +%s`.json"
    mkdir -p "${tmp_output_dir}"

    pairs="$1"
    scrapy runspider "${scrapy_folder}/investing-spider-alert-list.py" -o "${tmp_output_jsonfile}" --nolog
    python3 "${script_basedir}/investing-alert-view.py" "${tmp_output_jsonfile}" "$pairs"
}


###
### Main stuff
###

action="$2"

case "${action}" in
    "over" )
	match_pair "$1"
	msg=$(urlencode "$4");
	price=$(urlencode $3)
	send_alert "$action" "$price" "$msg";
	;;
    "under" )
	match_pair "$1"
	msg=$(urlencode "$4");
	price=$(urlencode $3)
	send_alert "$action" "$price" "$msg";
	;;
    "around" )
	match_pair "$1"
	price=$(urlencode $3)
	generate_alert_around "$price" "$4" "${5:-3}" "$6";
	;;
    "view" )
	if [ "$1" == "all" ]; then
	    view_alerts
	else
	    match_pairs "$1"	    
	    view_alerts "$pairs"
	fi
	;;
    * )
	echo "[error] Unknown action: '${action}'"
	usage
	exit 1
	;;
esac

