#!/usr/bin/env bash

script_name="$0"
indexes_file="${HOME}/.investing_com.indexes"
scrapy_folder="${HOME}/self/investing.com/spiders/"

#
#
#

function usage
{
    echo -e "[Usage]:\n\t${script_name}\n"
    echo -e "\tYou can setup INVESTING_COM_PORTFOLIO variable according to your portfolio ID from site.\n"
}

function view_portfolio
{
    tmp_output_dir="${HOME}/tmp/scrapy/"
    tmp_output_jsonfile="${tmp_output_dir}/investing.com_portfolio_`date +%s`.json"
    mkdir -p "${tmp_output_dir}"

    scrapy runspider "${scrapy_folder}/investing-spider-portfolio-list.py" -o "${tmp_output_jsonfile}" --nolog
    if [ -z "$1" ] || [ "$1" == "view" ]; then
	investing-portfolio-view "${tmp_output_jsonfile}"
    else
	investing-portfolio-panel "${tmp_output_jsonfile}"
    fi
}


###
### Main stuff
###

view_portfolio "$1"

